const {JSDOM,VirtualConsole}=require('jsdom');const fs=require('fs');
const html=fs.readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');
const mk=(pre)=>{ const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/scroll/.test(e.message))console.log('JSERR',e.message,e.detail&&e.detail.stack)});
  return new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'http://localhost/',virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;if(pre)pre(w);}}).window; };
(async()=>{
let w=mk(w=>{ w.localStorage.setItem('5k-plan-v1', JSON.stringify({dayRunType:{Mon:'Easy',Tue:'Rest',Wed:'Intervals',Thu:'Rest',Fri:'Tempo',Sat:'Rest',Sun:'Long'},strengthDays:['Mon','Thu','Sun'],completed:{1:{Mon:{run:true,strength:false,dog:true,steps:false}}},exLog:{}})); w.localStorage.setItem('5k-plan-selected',JSON.stringify({week:3,day:'Wed'})); });
let d=w.document;
console.log('migrated: title=',d.getElementById('planTitle').textContent,'| Mon run done:',w.eval('completed[1].Mon.run'),'| selected:',w.eval('JSON.stringify(selectedDay)'),'| tiles:',d.querySelectorAll('.tile').length,'| pace:',w.eval('goalPace()'));
await new Promise(r=>setTimeout(r,300));
const stored=JSON.parse(w.localStorage.getItem('5k-plan-store')); console.log('store plans:',stored.plans.length,'| active ok:',stored.activeId===stored.plans[0].plan.id);
d.getElementById('openPlans').click();
console.log('plans view open:',!d.getElementById('viewPlans').hidden,'| plan cards:',d.querySelectorAll('.plan-card').length,'| phase editors:',d.querySelectorAll('.ed-phase[data-phase]').length);
d.querySelector('[data-bind="name"]').value='10km Build'; d.querySelector('[data-bind="weeks"]').value='12'; d.querySelector('[data-bind="distanceKm"]').value='10'; d.querySelector('[data-bind="goalTime"]').value='52:00'; d.querySelector('[data-bind="currentPB"]').value='55:30';
d.getElementById('addPhase').click(); console.log('after add phase:',d.querySelectorAll('.ed-phase[data-phase]').length,'| name kept:',d.querySelector('[data-bind="name"]').value);
const phs=[...d.querySelectorAll('.ed-phase[data-phase]')]; const last=phs[phs.length-1]; last.querySelector('[data-bind$=".start"]').value='11'; last.querySelector('[data-bind$=".label"]').value='Race week';
phs[0].querySelector('[data-steps$="|Tempo"]').value='*Warm up* 12 min\n*Tempo* 18 min at 5:25/km\n*Cool down* 8 min';
d.getElementById('savePlan').click();
console.log('saved: err=',JSON.stringify(d.getElementById('edErr')?.textContent),'| back on plan:',!d.getElementById('viewPlan').hidden);
console.log('title:',d.getElementById('planTitle').textContent,'| sub:',d.getElementById('planSub').textContent);
console.log('tiles:',d.querySelectorAll('.tile').length,'(expect 84) | phase rows:',[...d.querySelectorAll('.phase-row')].map(x=>x.textContent).join(', '));
console.log('week 12 phase:',w.eval("phaseForWeek(12).label"),'| week 1 tempo steps:',w.eval("plan.guides.Tempo.sessions[plan.phases[0].id].join(' | ')"));
[...d.querySelectorAll('.tile')].find(t=>t.getAttribute('aria-label')==='Week 1 Fri').click();
console.log('panel steps:',d.querySelector('#dayPanel .runinfo ol')?.textContent.replace(/\s+/g,' ').trim());
d.getElementById('openPlans').click(); d.getElementById('newPlan').click();
console.log('new plan active:',w.eval('plan.name'),'| plans:',w.eval('store.plans.length'),'| Mon run done on new:',w.eval('completed[1].Mon.run'));
d.getElementById('closePlans').click(); d.getElementById('openPlans').click();
[...d.querySelectorAll('.plan-card')].find(c=>c.textContent.includes('10km Build')).querySelector('button').click();
console.log('switched back:',w.eval('plan.name'),'| Mon run done restored:',w.eval('completed[1].Mon.run'),'| weeks:',w.eval('plan.weeks'));
d.querySelector('[data-bind="weeks"]').value='0'; d.getElementById('savePlan').click(); console.log('validation:',d.getElementById('edErr').textContent);
d.querySelector('[data-bind="weeks"]').value='12'; d.getElementById('cancelPlan').click();
await new Promise(r=>setTimeout(r,300));
const raw=w.localStorage.getItem('5k-plan-store');
const w2=mk(w=>w.localStorage.setItem('5k-plan-store',raw));
console.log('reload:',w2.eval('plan.name'),'| plans:',w2.eval('store.plans.length'),'| Mon done:',w2.eval('completed[1].Mon.run'),'| tiles:',w2.document.querySelectorAll('.tile').length);
const snap=w2.eval('JSON.stringify(snapshot())'); const w3=mk(); w3.eval('applyData('+snap+')'); w3.render(); console.log('import into fresh:',w3.eval('plan.name'),w3.eval('store.plans.length'));
w2.document.getElementById('openPlans').click(); w2.document.getElementById('deletePlan').click(); console.log('after delete: plans=',w2.eval('store.plans.length'),'active=',w2.eval('plan.name'));
})();
